# Reference: https://git.mel.vin/template/c/commit/584b866fe79411b3f361e79fe0c0d68a3b278b9e

image: ubuntu

stages:
  - build
#  - test

variables:
  # https://askubuntu.com/questions/909277/avoiding-user-interaction-with-tzdata-when-installing-certbot-in-a-docker-contai
  DEBIAN_FRONTEND: "noninteractive"

build:
  stage: build
  before_script:
    - apt update && apt install -y build-essential g++ g++-multilib zlib1g-dev libminizip-dev libedit-dev gettext cmake git
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - make debug
  artifacts:
    paths:
    - bin/debug/HFWorkshop
    # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  cache:
    paths:
    - build/*.o

# run tests using the binary built before
#test:
#  stage: test
#  script:
#    - ./runmytests.sh

